compress by bzip2 by default, -b disables compression

diff --git a/pwned-pw-download b/pwned-pw-download
--- a/pwned-pw-download
+++ b/pwned-pw-download
@@ -10,13 +10,6 @@
 # the bottom level directors contain only 256 files each, plus a `curl.out' file
 # for diagnostic purposes.
 #
-# Please see `README.md` for more details.
-#
-# NOTE: It takes about 25 minutes to download the tree.
-#
-# NOTE: The tree contains 4369 directories and 1048576 files
-#	not including files such as curl.out and the top level repo files.
-#
 # This code came from the following GitHub repo:
 #
 #	https://github.com/lcn2/pwned-pw-download
@@ -104,7 +97,7 @@ shopt -s globstar	# enable ** to match all files and zero or more directories an
 
 # setup
 #
-export VERSION="1.2 2024-12-18"
+export VERSION="1.3 2025-12-03"
 NAME=$(basename "$0")
 export NAME
 #
@@ -113,6 +106,7 @@ export A_FLAG=
 export D_FLAG=
 export PARALLEL=64
 export BASE_RANGE_URL="https://api.pwnedpasswords.com/range"
+export B_FLAG=
 #
 CURL=$(type -P curl)
 export CURL
@@ -128,31 +122,34 @@ if [[ -z $DOS2UNIX ]]; then
     exit 7
 fi
 #
+BZIP2_PROG=$(type -P bzip2)
+export BZIP2_PROG
+if [[ -z $BZIP2_PROG ]]; then
+    echo "$0: ERROR: bzip2 command not found" 1>&2
+    exit 8
+fi
+#
 export EXIT_CODE=0
 
 # usage
 #
-export USAGE="usage: $0 [-h] [-v level] [-V] [-a] [-d] [-p parallel] [-U BASE_RANGE_URL] topdir
+export USAGE="usage: $0 [-h] [-v level] [-V] [-a] [-d] [-p parallel] [-U BASE_RANGE_URL] [-b] topdir
 
     -h          print help message and exit
     -v level    set verbosity level (def level: $V_FLAG)
     -V          print version string and exit
 
-    -a          do not append a final newline to downloaded files (def: do)
-    -d          do not un-DOS downloaded files (def: convert using $DOS2UNIX)
+    -a          do NOT append a final newline to downloaded files (def: do)
+    -d          do NOT un-DOS downloaded files (def: convert using $DOS2UNIX)
     -p parallel curl(1) files up to parallel at a time (def: $PARALLEL)
     -U base_url curl(1) files from under base_url (def: $BASE_RANGE_URL)
+    -b		do NOT bzip2 downloaded files (def: use $BZIP2_PROG on downloaded files)
 
     topdir      top of the 4-level pwned password tree to form
 
-    NOTE: It takes about 25 minutes to download the tree.
+    NOTE: For more information, see: https://github.com/lcn2/pwned-pw-download
 
-    NOTE: The tree contains 4369 directories and contains 1048576 files
-          not including files such as curl.out and the top level repo files.
-
-    NOTE: For more information see:
-
-        https://github.com/lcn2/pwned-pw-download
+    Try: pwned-pw-download -v 3 pwned.password.tree
 
 Exit codes:
      0         all OK
@@ -162,6 +159,7 @@ Exit codes:
      5         cannot make some directory under topdir
      6         some curl command exited non-zero
      7         some dos2unix command exited nonzero, or dos2unix command not found
+     8         some bzip2 command exited nonzero, or bzip2 command not found
  >= 10         internal error
 
 $NAME version: $VERSION"
@@ -169,7 +167,7 @@ $NAME version: $VERSION"
 
 # parse command line
 #
-while getopts :hv:Vadp:U: flag; do
+while getopts :hv:Vadp:U:b flag; do
   case "$flag" in
     h) echo "$USAGE"
 	exit 2
@@ -186,6 +184,8 @@ while getopts :hv:Vadp:U: flag; do
     p) PARALLEL="$OPTARG"
 	;;
     U) BASE_RANGE_URL="$OPTARG"
+	;;
+    b) B_FLAG="true"
 	;;
     \?) echo "$0: ERROR: invalid option: -$OPTARG" 1>&2
 	echo 1>&2
@@ -241,10 +241,12 @@ if [[ $V_FLAG -ge 3 ]]; then
     echo "$0: debug[3]: V_FLAG=$V_FLAG" 1>&2
     echo "$0: debug[3]: A_FLAG=$A_FLAG" 1>&2
     echo "$0: debug[3]: D_FLAG=$D_FLAG" 1>&2
+    echo "$0: debug[3]: B_FLAG=$B_FLAG" 1>&2
     echo "$0: debug[3]: PARALLEL=$PARALLEL" 1>&2
     echo "$0: debug[3]: BASE_RANGE_URL=$BASE_RANGE_URL" 1>&2
     echo "$0: debug[3]: CURL=$CURL" 1>&2
     echo "$0: debug[3]: DOS2UNIX=$DOS2UNIX" 1>&2
+    echo "$0: debug[3]: BZIP2_PROG=$BZIP2_PROG" 1>&2
     echo "$0: debug[3]: EXIT_CODE=$EXIT_CODE" 1>&2
     echo "$0: debug[3]: TOPDIR=$TOPDIR" 1>&2
 fi
@@ -337,8 +339,8 @@ for i in 0 1 2 3 4 5 6 7 8 9 A B C D E F; do
 
 	    # moderate debug
 	    #
-	    if [[ $V_FLAG -ge 2 ]]; then
-		echo "$0: debug[2]: processing: $i$j$k" 1>&2
+	    if [[ $V_FLAG -ge 3 ]]; then
+		echo "$0: debug[3]: processing: $i$j$k" 1>&2
 	    fi
 
 	    # paranoia - directory in the just created directory tree must exist
@@ -393,6 +395,25 @@ for i in 0 1 2 3 4 5 6 7 8 9 A B C D E F; do
 		find . -type f -name '[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]' -print | while read -r file; do
 		    echo "" >> "$file"
 		done
+	    fi
+
+	    # unless -b, bzip2 the file
+	    #
+	    if [[ -z $B_FLAG ]]; then
+		if [[ $V_FLAG -ge 5 ]]; then
+		    echo "$0: debug[5]: running: $BZIP2_PROG -z -q -f --best" [0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F] 1>&2
+		fi
+		"$BZIP2_PROG" -z -q -f --best [0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]
+		status="$?"
+		if [[ $status -ne 0 ]]; then
+		    echo "$0: Warning: $BZIP2_PROG -z -q -f --best in $TOPDIR/$i/$j/$k failed, error: $status" 1>&2
+		    EXIT_CODE=8 # exit 8
+		    echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
+		    echo "$0: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
+		fi
+		if [[ $V_FLAG -ge 5 ]]; then
+		    df . 1>&2
+		fi
 	    fi
 	done
     done
